name: ci1stlab testing
#Description: testing for ci 1st lab yml file
on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps: 
      - name: download code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: build code
        run: mvn package
      - name: run unit test
        run: mvn test
      - name: uploading artifact
        uses: actions/upload-artifact@v3
        with: 
          name: upload-target
          path: target
  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: downloading artifacts
        uses: actions/download-artifact@v3
      - name: deploy
        run: echo "deploy code"
       
